

    
    const workoutpackage = {
    0: {
        "Name" : "Men's Upper Body Strength",
        "Discription" : "Option 1",
        "forwho" : "male",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/mens_upperbody.jpg",
        "Exrecises" : [["Pull-Up", "10-12" , "3-5"], ["Incline Push-Up", "10-12", "3-5"], ["Seated Row", "10-12", "3-5"], ["Seated Biceps Curl", "10-12", "3-5"],
            ["Seated Chest Press", "10-12", "3-5"], ["Pullover With Crunch", "10-12", "3-5"], ["Snow Angle", "10-12", "3-5"], ["Lying Triceps Extension", "10-12", "3-5"]],
    },
    1: {
        "Name" : "Men's Upper Body Strength",
        "Discription" : "Option 2",
        "forwho" : "male",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/mens_upperbody2.jpg",
        "Exrecises" : [["Cross Cable Row", "10-12", "3-5"], ["Reverse Fly", "10-12", "3-5"], ["Inverted Front Raise", "10-12", "3-5"], ["Inverted Iron Cross", "10-12", "3-5"],
            ["Inverted Biceps Curl", "10-12", "3-5"], ["Oplique Twister", "10-12", "3-5"], ["Seated Chest Fly", "10-12", "3-5"], ["Lying Triceps", "10-12", "3-5"], ["Shoulder Press" , "10-12", "3-5"]],
    },
    2: {
        "Name" : "Women's 6-8 minute Strength",
        "Discription" : "",
        "forwho" : "female",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/womens_strength.jpg",
        "Exrecises" : [["Pull-Up", "8-10", "3-4"], ["Leg Curl", "8-10", "3-4"], ["Sit-Up", "8-10", "3-4"], ["Chin-up", "8-10", "3-4"],
            ["Cross Cable Row", "8-10", "3-4"], ["Oblique Twister" , "8-10", "3-4"], ["Front Pullover",  "8-10", "3-4"], ["Shoulder Press", "8-10", "3-4"]],
    },
    3: {
        "Name" : "Men's 6-8 minute Strength",
        "Discription" : "",
        "forwho" : "male",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/mens_strength.jpg",
        "Exrecises" : [["Pull-Up", "8-12", "4-6"], ["Leg Curl", "8-12", "4-6"], ["Sit-Up", "8-12", "4-6"], ["Chin-up", "8-12", "4-6"],
            ["Squat", , "8-12", "4-6"], ["Calf Raise" , "8-10", "3-4"], ["Oblique Twister", , "8-12", "4-6"], ["Shoulder Press", , "8-12", "4-6"]],
    },
    4: {
        "Name" : "Man's Lower Body Strength",
        "Discription" : "Option 1",
        "forwho" : "male",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/mens_lowerbody.jpg",
        "Exrecises" : [["Squat", "3-5" , "10-12"], ["Jumping Squat", "3-5" , "10-12"], ["Calf Raise", "3-5" , "10-12"], ["Single Leg Jumping Squat", "3-5" , "10-12"],
            ["Single Leg Calf Raise", "3-5" , "10-12"], ["Sprinter Start", "3-5" , "10-12"]],
    },
    5: {
        "Name" : "Men's Lower Body Strength",
        "Discription" : "Option 2",
        "forwho" : "male",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/mens_lowerbody2.jpg",
        "Exrecises" : [["Standing Lunge", "3-5" , "10-12"], ["Squat", "3-5" , "10-12"], ["Side Squat", "3-5" , "10-12"], ["Jumping Squat", "3-5" , "10-12"],
        ["Single Leg Jumping Squat", "3-5" , "10-12"], ["Lying Leg Curl", "3-5" , "10-12"]],
    },
    6: {
        "Name" : "Women's Lower Body Strength",
        "Discription" : "Option 1",
        "forwho" : "female",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/womens_lowerbody.jpg",
        "Exrecises" : [["Squat", "2-3" , "8-10"], ["Single Leg Squat", "2-3" , "8-10"], ["Calf Raise", "2-3" , "8-10"], ["Toe Out Squat", "2-3" , "8-10"],
            ["Jumping Squat", "2-3" , "8-10"], ["Lying Leg Curl with Cruch", "2-3" , "8-10"], ["Outer Hip and Thight", "2-3" , "8-10"]],
    },
    7: {
        "Name" : "Women's Lower Body Strength",
        "Discription" : "Option 2",
        "forwho" : "female",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/womens_lowerbody.jpg",
        "Exrecises" : [["Squat", "2-3" , "8-10"], ["Side Squat", "2-3" , "8-10"], ["Twisting Squat", "2-3" , "8-10"], ["Single Leg Jumping Squat", "2-3" , "8-10"],
        ["Hamstring Pull", "2-3" , "8-10"], ["Inner Thigh Pull", "2-3" , "8-10"], ["Core Extension", "2-3" , "8-10"]],
    },
    8: {
        "Name" : "Core Strength and Stabily",
        "Discription" : "option 1",
        "forwho" : "both",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/corestrength.jpg",
        "Exrecises" : [["Pullover With Crunch", "3" , "10-12"], ["Obliqu Pullover Crunch", "3" , "10-12"], ["Oblique Twisting", "3" , "10-12"], ["Toe Touch Row", "3" , "10-12"],
        ["Half Roll Back With Biceps Curl", "3" , "10-12"]],
    },
    9: {
        "Name" : "Core Strength and Stabily",
        "Discription" : "option 2",
        "forwho" : "both",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/corestrength.jpg",
        "Exrecises" : [["Surfer", "3" , "10-12"], ["Pullover With Crunch", "3" , "10-12"], ["Core Extension", "3" , "10-12"], ["Side Plank", "3" , "10-12"],
        ["Incline Push-Up", "3" , "10-12"],  ["Set-Up", "3" , "10-12"]],
    },
    10: {
        "Name" : "Kid's Workout",
        "Discription" : "option 1 - kids above the age of 8",
        "forwho" : "both",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/kids.jpg",
        "Exrecises" : [["Squat", "1-3" , "10-12"], ["Jumping Squat", "1-3" , "10-12"], ["Calf Raise", "1-3" , "10-12"], ["Front Pullover", "1-3" , "10-12"],
        ["Pullover With Crunch", "1-3" , "10-12"],  ["Lying Triceps Extension", "1-3" , "10-12"],  ["Seated Chest Press", "1-3" , "10-12"],  ["Shoulder Extension", "1-3" , "10-12"],
          ["Seated Biceps Curl", "1-3" , "10-12"]],
    },
    11: {
        "Name" : "Kid's Workout",
        "Discription" : "option 2 - kids above the age of 8",
        "forwho" : "both",
        "weeks" : "2-3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/kids2.jpg",
        "Exrecises" : [["Squat", "1-3" , "10-12"], ["Single Leg Squat", "1-3" , "10-12"], ["Single Leg Jumping Squat", "1-3" , "10-12"], ["Lying Leg Curl With Crunch", "1-3" , "10-12"],
        ["Pull-Up", "1-3" , "10-12"],  ["Incline Pull-Up", "1-3" , "10-12"],  ["Lying Triceps", "1-3" , "10-12"],  ["Seated Biceps Curl", "1-3" , "10-12"]],
    },
    12: {
        "Name" : "Biginner's Program",
        "Discription" : "For biginner lifters relatively new to the gym",
        "forwho" : "both",
        "weeks" : "3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/begginer.jpg",
        "Exrecises" : [["Barbell Bench Press", "3" , "8-10"], ["Barbell Back Squat", "3" , "8-10"], ["Pull-Ups", "3" , "6-10"], ["Lying Hamstring DB Curls", "3" , "10-15"],
        ["Standing Overhead Press", "3" , "6-10"],  ["Facepulls", "2" , "10-15"]],
    },
    13: {
        "Name" : "Advanced Program",
        "Discription" : "For experianced lifters who have a good foundation on musle and strength.",
        "forwho" : "both",
        "weeks" : "3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/advanced.jpg",
        "Exrecises" : [["Barbell Bench Press", "4" , "6-10"], ["Barbell Back Squat", "4" , "6-8"], ["Pull-Ups", "3" , "6-10"], ["Lying Hamstring DB Curls", "4" , "8-12"],
        ["Standing Overhead Press", "3" , "6-10"],  ["Facepulls", "4" , "10-15"],  ["Drag Curls", "3" , "8-10"]],
    },
    14: {
        "Name" : "Long and Lean",
        "Discription" : "Option 1 - Designed to strengthen your body while creating a longer leaner look.",
        "forwho" : "both",
        "weeks" : "3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/lean.jpg",
        "Exrecises" : [["Toe Bar Squat", "3" , "12-15"], ["Feet in V", "3" , "12-15"], ["Hip Roll", "3" , "12-15"], ["Roll-Up", "3" , "12-15"],
        ["Kneeling Plank Press", "3" , "12-15"],  ["Pullover With Crunch", "3" , "12-15"],  ["Seated Chest Fly", "3" , "12-15"],  ["Reverse Fly", "3" , "12-15"], 
         ["Lying Triceps Extension", "3" , "12-15"],  ["Half Roll Back With Biceps Curl", "3" , "12-15"]],
    },
    15: {
        "Name" : "Long and Lean",
        "Discription" : "Option 2 - Designed to strengthen your body while creating a longer leaner look.",
        "forwho" : "both",
        "weeks" : "3 times a week",
        "rest" : "2-3min",
        "img" : "imgs/workouts/lean2.jpg",
        "Exrecises" : [["Feet in V - Heels On Bar", "3" , "12-15"], ["Single Leg Squat", "3" , "12-15"], ["Single Leg Calf Raise", "3" , "12-15"], ["Standing Lunge", "3" , "12-15"],
        ["Side Plank", "3" , "12-15"],  ["Core Extension", "3" , "12-15"],  ["Inner Thigh Pull", "3" , "12-15"],  ["Hamstring Pull", "3" , "12-15"]],
    },
   
  
  
   }


export default workoutpackage;